name: CI
on: push
env:
  CONFIGURATION: release
jobs:
  test-mac:
    strategy:
      matrix:
        test: [SwiftShogiTests, PerformanceTests]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: swift test
      run: swift test -c $CONFIGURATION -Xswiftc -enable-testing --filter ${{ matrix.test }}
  test-linux:
    strategy:
      matrix:
        test: [SwiftShogiTests, PerformanceTests]
    runs-on: ubuntu-latest
    container: swift:5.1-bionic
    steps:
    - uses: actions/checkout@v2
    - name: swift test
      run: swift test -c $CONFIGURATION -Xswiftc -enable-testing --filter ${{ matrix.test }}
