name: CI
on: push
jobs:
  test-mac:
    strategy:
      matrix:
        test: [SwiftShogiTests, PerformanceTests]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: swift test -c $CONFIGURATION -Xswiftc -enable-testing --enable-code-coverage --filter ${{ matrix.test }}
    - name: Upload coverage
      if: matrix.test == 'SwiftShogiTests'
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./.build/release/codecov/SwiftShogi.json
  test-linux:
    strategy:
      matrix:
        test: [SwiftShogiTests, PerformanceTests]
    runs-on: ubuntu-latest
    container: swift:5.1-bionic
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: swift test -c $CONFIGURATION -Xswiftc -enable-testing --filter ${{ matrix.test }}
env:
  CONFIGURATION: release
